// <auto-generated />
using System;
using ClosedXML.Report.Sample.Contexts.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClosedXML.Report.Sample.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20200909114032_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("ClosedXML.Report.Sample.Entities.Sqlite.ProductEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .HasColumnName("barcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnName("code")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("createdAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedBy")
                        .HasColumnName("createdBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnName("isActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnName("price")
                        .HasColumnType("REAL");

                    b.Property<double>("Quantity")
                        .HasColumnName("quantity")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnName("updatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedBy")
                        .HasColumnName("updatedBy")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("m_product");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Barcode = "8850125082311",
                            Code = "8850125082311",
                            CreatedAt = new DateTime(2020, 9, 9, 18, 40, 32, 523, DateTimeKind.Local).AddTicks(5236),
                            CreatedBy = 1L,
                            IsActive = true,
                            Name = "ไมโล เครื่องดื่มช็อกโกแลตมอลต์ปรุงสำเร็จชนิดผง สูตรน้ำตาลน้อย 25 กรัม แพ็ค 15",
                            Price = 98.0,
                            Quantity = 100.0,
                            UpdatedAt = new DateTime(2020, 9, 9, 18, 40, 32, 524, DateTimeKind.Local).AddTicks(5098),
                            UpdatedBy = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Barcode = "8851959632185",
                            Code = "8851959632185",
                            CreatedAt = new DateTime(2020, 9, 9, 18, 40, 32, 524, DateTimeKind.Local).AddTicks(5814),
                            CreatedBy = 1L,
                            IsActive = true,
                            Name = "แฟนต้า น้ำอัดลม น้ำเขียว 325 มล. 6 กระป๋อง",
                            Price = 72.0,
                            Quantity = 200.0,
                            UpdatedAt = new DateTime(2020, 9, 9, 18, 40, 32, 524, DateTimeKind.Local).AddTicks(5843),
                            UpdatedBy = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Barcode = "8850250004943",
                            Code = "8850250004943",
                            CreatedAt = new DateTime(2020, 9, 9, 18, 40, 32, 524, DateTimeKind.Local).AddTicks(5858),
                            CreatedBy = 1L,
                            IsActive = true,
                            Name = "ยำยำ บะหมี่กึ่งสำเร็จรูป รสต้มยำกุ้ง 67 ก. แพ็ค",
                            Price = 48.0,
                            Quantity = 300.0,
                            UpdatedAt = new DateTime(2020, 9, 9, 18, 40, 32, 524, DateTimeKind.Local).AddTicks(5859),
                            UpdatedBy = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Barcode = "8850006322499",
                            Code = "8850006322499",
                            CreatedAt = new DateTime(2020, 9, 9, 18, 40, 32, 524, DateTimeKind.Local).AddTicks(5862),
                            CreatedBy = 1L,
                            IsActive = true,
                            Name = "คอลเกต ยาสีฟัน สูตรเกลือสมุนไพร 150 กรัม แพ็ค 2",
                            Price = 99.0,
                            Quantity = 400.0,
                            UpdatedAt = new DateTime(2020, 9, 9, 18, 40, 32, 524, DateTimeKind.Local).AddTicks(5863),
                            UpdatedBy = 1L
                        },
                        new
                        {
                            Id = 5L,
                            Barcode = "8888336032917",
                            Code = "8888336032917",
                            CreatedAt = new DateTime(2020, 9, 9, 18, 40, 32, 524, DateTimeKind.Local).AddTicks(5865),
                            CreatedBy = 1L,
                            IsActive = true,
                            Name = "ฮักกี้ส์ โกลด์ ซอฟท์แอนด์สลิม แพ้นท์ กางเกงผ้าอ้อมเด็ก ขนาด XL แพ็ค 38 ชิ้น",
                            Price = 449.0,
                            Quantity = 500.0,
                            UpdatedAt = new DateTime(2020, 9, 9, 18, 40, 32, 524, DateTimeKind.Local).AddTicks(5867),
                            UpdatedBy = 1L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
